COUNTRIES =[('AFG', 'Afghanistan'),
            ('ALB', 'Albania'),
            ('ALG', 'Algeria'),
            ('AMS', 'American Samoa'),
            ('AND', 'Andorra'),
            ('ANG', 'Angola'),
            ('ANL', 'Anguilla'),
            ('ANT', 'Antigua & Barbuda'),
            ('ARG', 'Argentina'),
            ('ARM', 'Armenia'),
            ('ARU', 'Aruba'),
            ('AUS', 'Australia'),
            ('AUT', 'Austria'),
            ('AZE', 'Azerbaijan'),
            ('BAH', 'Bahamas'),
            ('BHR', 'Bahrain'),
            ('BAN', 'Bangladesh'),
            ('BAR', 'Barbados'),
            ('BER', 'Belarus'),
            ('BEG', 'Belgium'),
            ('BEL', 'Belize'),
            ('BEN', 'Benin'),
            ('BER', 'Bermuda'),
            ('BHU', 'Bhutan'),
            ('BOL', 'Bolivia'),
            ('BOS', 'Bosnia & Herzegovina'),
            ('BOT', 'Botswana'),
            ('BRA', 'Brazil'),
            ('BVI', 'British Virgin Is.'),
            ('BRU', 'Brunei'),
            ('BUL', 'Bulgaria'),
            ('BKF', 'Burkina Faso'),
            ('BUM', 'Burma'),
            ('BUR', 'Burundi'),
            ('CMD', 'Cambodia'),
            ('CAM', 'Cameroon'),
            ('CAN', 'Canada'),
            ('CPV', 'Cape Verde'),
            ('CYM', 'Cayman Islands'),
            ('CAR', 'Central African Rep.'),
            ('CHD', 'Chad'),
            ('CHL', 'Chile'),
            ('CHN', 'China'),
            ('COL', 'Colombia'),
            ('COM', 'Comoros'),
            ('CDR', 'Congo Dem.Rep.'),
            ('CKI', 'Cook Islands'),
            ('CSR', 'Costa Rica'),
            ('CTI', 'Cote d''Ivoire'),
            ('CRT', 'Croatia'),
            ('CUB', 'Cuba'),
            ('CYP', 'Cyprus'),
            ('CZR', 'Czech Republic'),
            ('DEN', 'Denmark'),
            ('DJB', 'Djibouti'),
            ('DOM', 'Dominica'),
            ('DMR', 'Dominican Republic'),
            ('ETM', 'East Timor'),
            ('ECQ', 'Ecuador'),
            ('EGY', 'Egypt'),
            ('ESV', 'El Salvador'),
            ('EQG', 'Equatorial Guinea'),
            ('ERT', 'Eritrea'),
            ('EST', 'Estonia'),
            ('ETH', 'Ethiopia'),
            ('FRI', 'Faroe Islands'),
            ('FIJ', 'Fiji'),
            ('FIN', 'Finland'),
            ('FRA', 'France'),
            ('FRG', 'French Guiana'),
            ('FRP', 'French Polynesia'),
            ('GAB', 'Gabon'),
            ('GMB', 'Gambia'),
            ('GZS', 'Gaza Strip'),
            ('GEO', 'Georgia'),
            ('GER', 'Germany'),
            ('GHA', 'Ghana'),
            ('GIB', 'Gibraltar'),
            ('GRE', 'Greece'),
            ('GRN', 'Greenland'),
            ('GRD', 'Grenada'),
            ('GUD', 'Guadeloupe'),
            ('GUM', 'Guam'),
            ('GUA', 'Guatemala'),
            ('GUE', 'Guernsey'),
            ('GUI', 'Guinea'),
            ('GNB', 'Guinea-Bissau'),
            ('GUY', 'Guyana'),
            ('HAI', 'Haiti'),
            ('HON', 'Honduras'),
            ('HKG', 'HongKong'),
            ('HUN', 'Hungary'),
            ('ICE', 'Iceland'),
            ('IND', 'India'),
            ('IDS', 'Indonesia'),
            ('IRN', 'Iran'),
            ('IRQ', 'Iraq'),
            ('IRE', 'Ireland'),
            ('ISM', 'Isle of Man'),
            ('ISR', 'Israel'),
            ('ITA', 'Italy'),
            ('JAM', 'Jamaica'),
            ('JAP', 'Japan'),
            ('JER', 'Jersey'),
            ('JOR', 'Jordan'),
            ('KAZ', 'Kazakhstan'),
            ('KEN', 'Kenya'),
            ('KIR', 'Kiribati'),
            ('NKR', 'Korea North'),
            ('SKR', 'Korea South'),
            ('KWT', 'Kuwait'),
            ('KYR', 'Kyrgyzstan'),
            ('LAO', 'Laos'),
            ('LAT', 'Latvia'),
            ('LEB', 'Lebanon'),
            ('LES', 'Lesotho'),
            ('LIB', 'Liberia'),
            ('LBA', 'Libya'),
            ('LCT', 'Liechtenstein'),
            ('LIT', 'Lithuania'),
            ('LUX', 'Luxembourg'),
            ('MAC', 'Macau'),
            ('MCD', 'Macedonia'),
            ('MAD', 'Madagascar'),
            ('MLW', 'Malawi'),
            ('MAL', 'Malaysia'),
            ('MLD', 'Maldives'),
            ('MLI', 'Mali'),
            ('MLT', 'Malta'),
            ('MSI', 'Marshall Islands'),
            ('MRQ', 'Martinique'),
            ('MRT', 'Mauritania'),
            ('MAU', 'Mauritius'),
            ('MYT', 'Mayotte'),
            ('MEX', 'Mexico'),
            ('MIC', 'Micronesia Fed. St.'),
            ('MOL', 'Moldova'),
            ('MON', 'Monaco'),
            ('MNG', 'Mongolia'),
            ('MNT', 'Montserrat'),
            ('MOR', 'Morocco'),
            ('MOZ', 'Mozambique'),
            ('NAM', 'Namibia'),
            ('NAR', 'Nauru'),
            ('NEP', 'Nepal'),
            ('NET', 'Netherlands'),
            ('NTA', 'Netherlands Antilles'),
            ('NWC', 'New Caledonia'),
            ('NZL', 'New Zealand'),
            ('NIC', 'Nicaragua'),
            ('NGR', 'Niger'),
            ('NIG', 'Nigeria'),
            ('NMI', 'N. Mariana Islands'),
            ('NRW', 'Norway'),
            ('OMN', 'Oman'),
            ('PAK', 'Pakistan'),
            ('PAL', 'Palau'),
            ('PAN', 'Panama'),
            ('PNG', 'Papua New Guinea'),
            ('PAR', 'Paraguay'),
            ('PER', 'Peru'),
            ('PHI', 'Philippines'),
            ('POL', 'Poland'),
            ('POR', 'Portugal'),
            ('PTR', 'Puerto Rico'),
            ('QTR', 'Qatar'),
            ('REU', 'Reunion'),
            ('ROM', 'Romania'),
            ('RUS', 'Russia'),
            ('RWD', 'Rwanda'),
            ('SHL', 'Saint Helena'),
            ('SKN', 'Saint Kitts & Nevis'),
            ('SLC', 'Saint Lucia'),
            ('STP', 'St Pierre & Miquelon'),
            ('STV', 'Saint Vincent and the Grenadines'),
            ('SAM', 'Samoa'),
            ('SNM', 'San Marino'),
            ('STM', 'Sao Tome & Principe'),
            ('SAU', 'Saudi Arabia'),
            ('SEN', 'Senegal'),
            ('SER', 'Serbia'),
            ('SEY', 'Seychelles'),
            ('SRL', 'Sierra Leone'),
            ('SNG', 'Singapore'),
            ('SLK', 'Slovakia'),
            ('SLV', 'Slovenia'),
            ('SOL', 'Solomon Islands'),
            ('SOM', 'Somalia'),
            ('STA', 'South Africa'),
            ('SPA', 'Spain'),
            ('SRL', 'Sri Lanka'),
            ('SUD', 'Sudan'),
            ('SUR', 'Suriname'),
            ('SWA', 'Swaziland'),
            ('SWE', 'Sweden'),
            ('SWI', 'Switzerland'),
            ('SYR', 'Syria'),
            ('TAI', 'Taiwan'),
            ('TAJ', 'Tajikistan'),
            ('TAN', 'Tanzania'),
            ('THA', 'Thailand'),
            ('TOG', 'Togo'),
            ('TON', 'Tonga'),
            ('TRI', 'Trinidad & Tobago'),
            ('TUN', 'Tunisia'),
            ('TUR', 'Turkey'),
            ('TRK', 'Turkmenistan'),
            ('TKC', 'Turks & Caicos Is'),
            ('TUV', 'Tuvalu'),
            ('UGA', 'Uganda'),
            ('UKR', 'Ukraine'),
            ('UAE', 'United Arab Emirates'),
            ('UKG', 'United Kingdom'),
            ('USA', 'United States'),
            ('URU', 'Uruguay'),
            ('UZB', 'Uzbekistan'),
            ('VAN', 'Vanuatu'),
            ('VEN', 'Venezuela'),
            ('VTN', 'Vietnam'),
            ('VRG', 'Virgin Islands'),
            ('WLF', 'Wallis and Futuna'),
            ('WBK', 'West Bank'),
            ('WSS', 'Western Sahara'),
            ('YEM', 'Yemen'),
            ('ZMB', 'Zambia'),
            ('ZBW', 'Zimbabwe')
            ]

TYPES = [('Private', 'Private Customer'),
         ('Company', 'Company Customer')]